export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_SUCCESS = 'API_CALL_SUCCESS';
export const API_CALL_ERROR = 'API_CALL_ERROR';

export const UNAUTHORIZED = 'UNAUTHORIZED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const SAVE_LAND_TILE_SUCCESS = 'SAVE_LAND_TILE_SUCCESS';
